### ISSUE TITLE
Copy/Preview errors and does nothing

### ISSUE THREAD

**Issue by kanielrkirby** [mondeja/simple-icons-website-rs#243]
### Kind of issue 

- [ ] Feature
- [x] Bug
- [ ] Design
- [ ] Other, namely:

### Description

Browser: `Chromium 126.0.6478.114`

Steps to reproduce (for me, at least):

- Navigate to [the preview viewer](https://wasm.simpleicons.org/preview).
- Press "Save Preview" or "Copy Preview".

### First Load

```
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'run-ad-auction'.
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'join-ad-interest-group'.
```

### Save Preview

```
simple-icons-website-3f82880105436c5f.js:545 panicked at components/src/preview_generator/buttons.rs:210:48:
called `Result::unwrap()` on an `Err` value: JsValue(SecurityError: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.
Error: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.
    at https://wasm.simpleicons.org/simple-icons-website-3f82880105436c5f.js:1155:33
    at handleError (https://wasm.simpleicons.org/simple-icons-website-3f82880105436c5f.js:316:18)
    at imports.wbg.__wbg_toDataURL_07e0b35272e75f05 (https://wasm.simpleicons.org/simple-icons-website-3f82880105436c5f.js:1154:68)
    at https://wasm.simpleicons.org/simple-icons-website-3f82880105436c5f_bg.wasm:wasm-function[1249]:0x14e575
    at https://wasm.simpleicons.org/simple-icons-website-3f82880105436c5f_bg.wasm:wasm-function[3424]:0x1d580f
    at https://wasm.simpleicons.org/simple-icons-website-3f82880105436c5f_bg.wasm:wasm-function[2572]:0x1b3519
    at https://wasm.simpleicons.org/simple-icons-website-3f82880105436c5f_bg.wasm:wasm-function[3436]:0x1d637e
    at https://wasm.simpleicons.org/simple-icons-website-3f82880105436c5f_bg.wasm:wasm-function[2908]:0x1cd62f
    at __wbg_adapter_63 (https://wasm.simpleicons.org/simple-icons-website-3f82880105436c5f.js:279:10)
    at HTMLButtonElement.real (https://wasm.simpleicons.org/simple-icons-website-3f82880105436c5f.js:215:20))

Stack:

Error
    at imports.wbg.__wbg_new_abda76e883ba8a5f (https://wasm.simpleicons.org/simple-icons-website-3f82880105436c5f.js:532:21)
    at https://wasm.simpleicons.org/simple-icons-website-3f82880105436c5f_bg.wasm:wasm-function[3378]:0x1d4822
    at https://wasm.simpleicons.org/simple-icons-website-3f82880105436c5f_bg.wasm:wasm-function[1640]:0x18d046
    at https://wasm.simpleicons.org/simple-icons-website-3f82880105436c5f_bg.wasm:wasm-function[2632]:0x1b522c
    at https://wasm.simpleicons.org/simple-icons-website-3f82880105436c5f_bg.wasm:wasm-function[2114]:0x1a4e2a
    at https://wasm.simpleicons.org/simple-icons-website-3f82880105436c5f_bg.wasm:wasm-function[1249]:0x14e656
    at https://wasm.simpleicons.org/simple-icons-website-3f82880105436c5f_bg.wasm:wasm-function[3424]:0x1d580f
    at https://wasm.simpleicons.org/simple-icons-website-3f82880105436c5f_bg.wasm:wasm-function[2572]:0x1b3519
    at https://wasm.simpleicons.org/simple-icons-website-3f82880105436c5f_bg.wasm:wasm-function[3436]:0x1d637e
    at https://wasm.simpleicons.org/simple-icons-website-3f82880105436c5f_bg.wasm:wasm-function[2908]:0x1cd62f


imports.wbg.__wbg_error_f851667af71bcfc6 @ simple-icons-website-3f82880105436c5f.js:545
$func3378 @ simple-icons-website-3f82880105436c5f_bg.wasm:0x1d4928
$func1640 @ simple-icons-website-3f82880105436c5f_bg.wasm:0x18d046
$func2632 @ simple-icons-website-3f82880105436c5f_bg.wasm:0x1b522c
$func2114 @ simple-icons-website-3f82880105436c5f_bg.wasm:0x1a4e2a
$func1249 @ simple-icons-website-3f82880105436c5f_bg.wasm:0x14e656
$func3424 @ simple-icons-website-3f82880105436c5f_bg.wasm:0x1d580f
$func2572 @ simple-icons-website-3f82880105436c5f_bg.wasm:0x1b3519
$func3436 @ simple-icons-website-3f82880105436c5f_bg.wasm:0x1d637e
$_dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h1cce5f7ed142ca20 @ simple-icons-website-3f82880105436c5f_bg.wasm:0x1cd62f
__wbg_adapter_63 @ simple-icons-website-3f82880105436c5f.js:279
real @ simple-icons-website-3f82880105436c5f.js:215
simple-icons-website-3f82880105436c5f_bg.wasm:0x18d06c Uncaught RuntimeError: unreachable
    at simple-icons-website-3f82880105436c5f_bg.wasm:0x18d06c
    at simple-icons-website-3f82880105436c5f_bg.wasm:0x1b522c
    at simple-icons-website-3f82880105436c5f_bg.wasm:0x1a4e2a
    at simple-icons-website-3f82880105436c5f_bg.wasm:0x14e656
    at simple-icons-website-3f82880105436c5f_bg.wasm:0x1d580f
    at simple-icons-website-3f82880105436c5f_bg.wasm:0x1b3519
    at simple-icons-website-3f82880105436c5f_bg.wasm:0x1d637e
    at simple-icons-website-3f82880105436c5f_bg.wasm:0x1cd62f
    at __wbg_adapter_63 (simple-icons-website-3f82880105436c5f.js:279:10)
    at HTMLButtonElement.real (simple-icons-website-3f82880105436c5f.js:215:20)
$func1640 @ simple-icons-website-3f82880105436c5f_bg.wasm:0x18d06c
$func2632 @ simple-icons-website-3f82880105436c5f_bg.wasm:0x1b522c
$func2114 @ simple-icons-website-3f82880105436c5f_bg.wasm:0x1a4e2a
$func1249 @ simple-icons-website-3f82880105436c5f_bg.wasm:0x14e656
$func3424 @ simple-icons-website-3f82880105436c5f_bg.wasm:0x1d580f
$func2572 @ simple-icons-website-3f82880105436c5f_bg.wasm:0x1b3519
$func3436 @ simple-icons-website-3f82880105436c5f_bg.wasm:0x1d637e
$_dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h1cce5f7ed142ca20 @ simple-icons-website-3f82880105436c5f_bg.wasm:0x1cd62f
__wbg_adapter_63 @ simple-icons-website-3f82880105436c5f.js:279
real @ simple-icons-website-3f82880105436c5f.js:215
```

### Copy Preview

```
panicked at components/src/copy.rs:61:57:
called `Result::unwrap()` on an `Err` value: JsValue(SecurityError: Failed to execute 'toBlob' on 'HTMLCanvasElement': Tainted canvases may not be exported.
Error: Failed to execute 'toBlob' on 'HTMLCanvasElement': Tainted canvases may not be exported.
    at https://wasm.simpleicons.org/simple-icons-website-3f82880105436c5f.js:1152:21
    at handleError (https://wasm.simpleicons.org/simple-icons-website-3f82880105436c5f.js:316:18)
    at imports.wbg.__wbg_toBlob_8adeddb6976528a5 (https://wasm.simpleicons.org/simple-icons-website-3f82880105436c5f.js:1151:65)
    at https://wasm.simpleicons.org/simple-icons-website-3f82880105436c5f_bg.wasm:wasm-function[1848]:0x19c2fa
    at https://wasm.simpleicons.org/simple-icons-website-3f82880105436c5f_bg.wasm:wasm-function[1019]:0x1311db
    at https://wasm.simpleicons.org/simple-icons-website-3f82880105436c5f_bg.wasm:wasm-function[3436]:0x1d637e
    at https://wasm.simpleicons.org/simple-icons-website-3f82880105436c5f_bg.wasm:wasm-function[2922]:0x1cd76e
    at __wbg_adapter_95 (https://wasm.simpleicons.org/simple-icons-website-3f82880105436c5f.js:303:10)
    at real (https://wasm.simpleicons.org/simple-icons-website-3f82880105436c5f.js:215:20))

Stack:

Error
    at imports.wbg.__wbg_new_abda76e883ba8a5f (https://wasm.simpleicons.org/simple-icons-website-3f82880105436c5f.js:532:21)
    at https://wasm.simpleicons.org/simple-icons-website-3f82880105436c5f_bg.wasm:wasm-function[3378]:0x1d4822
    at https://wasm.simpleicons.org/simple-icons-website-3f82880105436c5f_bg.wasm:wasm-function[1640]:0x18d046
    at https://wasm.simpleicons.org/simple-icons-website-3f82880105436c5f_bg.wasm:wasm-function[2632]:0x1b522c
    at https://wasm.simpleicons.org/simple-icons-website-3f82880105436c5f_bg.wasm:wasm-function[2114]:0x1a4e2a
    at https://wasm.simpleicons.org/simple-icons-website-3f82880105436c5f_bg.wasm:wasm-function[1848]:0x19c390
    at https://wasm.simpleicons.org/simple-icons-website-3f82880105436c5f_bg.wasm:wasm-function[1019]:0x1311db
    at https://wasm.simpleicons.org/simple-icons-website-3f82880105436c5f_bg.wasm:wasm-function[3436]:0x1d637e
    at https://wasm.simpleicons.org/simple-icons-website-3f82880105436c5f_bg.wasm:wasm-function[2922]:0x1cd76e
    at __wbg_adapter_95 (https://wasm.simpleicons.org/simple-icons-website-3f82880105436c5f.js:303:10)


imports.wbg.__wbg_error_f851667af71bcfc6 @ simple-icons-website-3f82880105436c5f.js:545
$func3378 @ simple-icons-website-3f82880105436c5f_bg.wasm:0x1d4928
$func1640 @ simple-icons-website-3f82880105436c5f_bg.wasm:0x18d046
$func2632 @ simple-icons-website-3f82880105436c5f_bg.wasm:0x1b522c
$func2114 @ simple-icons-website-3f82880105436c5f_bg.wasm:0x1a4e2a
$func1848 @ simple-icons-website-3f82880105436c5f_bg.wasm:0x19c390
$func1019 @ simple-icons-website-3f82880105436c5f_bg.wasm:0x1311db
$func3436 @ simple-icons-website-3f82880105436c5f_bg.wasm:0x1d637e
$_dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__ha78d7a0d4fb3ac95 @ simple-icons-website-3f82880105436c5f_bg.wasm:0x1cd76e
__wbg_adapter_95 @ simple-icons-website-3f82880105436c5f.js:303
real @ simple-icons-website-3f82880105436c5f.js:215
simple-icons-website-3f82880105436c5f_bg.wasm:0x18d06c Uncaught RuntimeError: unreachable
    at simple-icons-website-3f82880105436c5f_bg.wasm:0x18d06c
    at simple-icons-website-3f82880105436c5f_bg.wasm:0x1b522c
    at simple-icons-website-3f82880105436c5f_bg.wasm:0x1a4e2a
    at simple-icons-website-3f82880105436c5f_bg.wasm:0x19c390
    at simple-icons-website-3f82880105436c5f_bg.wasm:0x1311db
    at simple-icons-website-3f82880105436c5f_bg.wasm:0x1d637e
    at simple-icons-website-3f82880105436c5f_bg.wasm:0x1cd76e
    at __wbg_adapter_95 (simple-icons-website-3f82880105436c5f.js:303:10)
    at real (simple-icons-website-3f82880105436c5f.js:215:20)
```

---

Every other button on the page works just fine with no console output.

**Comment by kanielrkirby** [comment]
Now that I look closer at the error, I've had this issue with other websites that make use of canvas (Figma, namely). I wonder what it is...

**Comment by mondeja** [comment]
Are you using uBlock Origin?

**Comment by kanielrkirby** [comment]
I figured this out recently, it was one of the policies I set on Chromium way back, totally my fault. Don't even remember what policy it was. I'll check this specific site when I get back to my problem machine to make sure this isn't still an issue, but I suspect not. Thanks for the check-in, or else I would have forgotten to get back to y'all!
